version: '3.8'
networks:
  main-network:
    external: true

volumes:
  pgsql-volume:
    external: true

services:
  pgsql-db:
    image: postgres:latest
    container_name: pgsql-db
    restart: always
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_PASSWORD: pupokbomja
    volumes:
      - pgsql-volume:/var/lib/postgresql/data
    networks:
      - main-network

  laravel-app:
    build:
      context: /var/www/bettercallcrm
      dockerfile: dockerfile
    container_name: laravel-app
    restart: always
    depends_on:
      - pgsql-db
    networks:
      - main-network

  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    depends_on:
      - laravel-app
    networks:
      - main-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/BetterCallCRMFrontend/dist:/usr/share/nginx/html
      - ~/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/nginx/cert:/etc/letsencrypt/live/labzavr.ru
